services:
  teste-mongo:
    restart: unless-stopped
    container_name: teste-mongo
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - vol-db:/data/db

# Este container é utilizado para testes, não é necessário para o funcionamento da aplicação, para rodar os testes
#
# https://github.com/rroemhild/docker-test-openldap
# OpenLDAP Docker Image for testing
# This Docker image provides an OpenLDAP Server for testing LDAP applications, i.e. unit tests. 
# The server is initialized with the example domain planetexpress.com with data from the Futurama Wiki.
  teste-openldap:
    container_name: teste-openldap
    restart: unless-stopped
    image: ghcr.io/rroemhild/docker-test-openldap:master
    ports:
      - "10389:10389"
      - "10636:10636"
    environment:
      - LDAP_BINDDN=cn=admin,dc=planetexpress,dc=com
      - LDAP_BASE_SEARCH=ou=people,dc=planetexpress,dc=com


volumes:
  vol-db: